import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "../components/Products";
import { Gallery } from "../styles/Gallery";
import { useRef } from "react";
import About from "../components/About";

export default function Home() {
  //Fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  const resultRef = useRef(null);

  //Check for the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  const products = data.products.data;

  return (
    <>
      <Head>
        <title>DiscHive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          type="image/x-icon"
          rel="shortcut icon"
          href="/images/favicon.ico"
        />
      </Head>

      <main>
        <About resultRef={resultRef} />
        <h2 style={{ color: "red" }}>
          This is a demo. Purchases will not be made!
        </h2>
        <Gallery>
          {products.map((product) => (
            <Products
              key={product.attributes.slug}
              product={product}
              ref={resultRef}
            />
          ))}
        </Gallery>
      </main>
    </>
  );
}
